### PR TITLE
Support for the reMarkable2 with high fps.

### PR DESCRIPTION
**Pull request by Foxei**
Hello everyone,
this is a working solution for the issue #28 and is a addition to the pull request #31. The code is tested on a reMarkable2 and working with 12-14 fps which is a great improvement over the 2-3fps with the current solution. The `dd`, `head` and `tail` combination is replace with a custom C program that dumps the memory. The executable `reDump` is Open Source and can be found [here](https://github.com/Foxei/reDump/).

- [ ] Confirm this doesn't break rM1 support.
- [x] Confirmed working on a rM2 in landscape and portrait mode.

https://user-images.githubusercontent.com/25650006/103320344-41a53400-4a35-11eb-9d14-d1d096111356.mp4

### CODE REVIEW

**Comment by Lxstr** [comment]
Tested this and seems quite fast. Although the image quality is definitely lower than rmview. I haven't compared to the main branch of restream though. Is there anyway to easily check fps and resolution during testing?

**Comment by Foxei** [comment]
Hello @Lxstr,
to my knowledge bordeigol has not yet merged ssh support for the remarkable 2 into the main rmView project. Which fork of rmView have you compared this to? 

It might be though that there is a difference in scaling. reStream uses the ffplay command to display and scale the image and rmView performers the scaling with a QGraphivsView. This most certainly makes a difference but I honestly do not know to what extent. 

I have to fail you here because I do not know if ffplay even supports displaying such statistics. I may have to correct my statement in the pull request. I cannot ensure that actually 12-14 FPS are displayed I only can ensure that reDump and lz4 are making the image available with 12-14 FPS. If the receiving side can handle that is not my job anymore. 😄

**Comment by rien** [comment]
Hi @Foxei, thank you for the PR! (And thank you for poking me to perform my duties as a maintainer.)

Unfortunately, I have made a program like `reDump` already in Rust, and prefer to use my own version.  I hope you understand.

My apologies for not releasing it earlier and saving you this work.

**Comment by Foxei** [comment]
Hello @rien,
I understand no hard feelings. 😉 Do not think I will not try to make additions to you work in the future though. I love this hole streaming and dumping think.

**Pull request closed without merging**
